{{- if and .Values.networkPolicy.enabled .Values.networkPolicy.ciliumNodeLocalDNS }}
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: {{ .Release.Name }}-node-local-dns
spec:
  endpointSelector:
    matchLabels:
      app.kubernetes.io/instance: {{ .Release.Name }}
  egress:
    - toEntities:
        - host
      toPorts:
        - ports:
            - port: "53"
              protocol: UDP
            - port: "53"
              protocol: TCP
{{- end }}
